name: Format Files

on:
  workflow_run:
    workflows: ["Install Dependencies"]
    types:
      - completed

jobs:
  format_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Format files with Prettier
        run: |
          IFS=' ' read -r -a files <<< "${{ github.event.outputs.files }}"
          for file in "${files[@]}"; do
            if [ -f "$file" ]; then
              case "$file" in
                *.xml) npx prettier --write "$file" --parser xml ;;
                *.json) npx prettier --write "$file" --parser json ;;
                *.yaml|*.yml) npx prettier --write "$file" --parser yaml ;;
                *) echo "Skipping $file (not an XML, JSON, or YAML file)" ;;
              esac || { echo "Failed to format $file"; exit 1; }
            else
              echo "$file does not exist."
            fi
          done
