name: NitrAPI PSA

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  fetch_notifications:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Install the requests library

    - name: Run fetch notifications script
      env:
        NITRADO_TOKEN: ${{ secrets.NITRADO_TOKEN }}  # Add your secret token here
      run: |
        python fetch_notifications.py  # Make sure the script name matches
