name: NitrAPI Restart Gameserver

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  restart_gameserver:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # You can change this to your required version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Install the requests library

    - name: Run gameserver restart script
      env:
        NITRADO_TOKEN: ${{ secrets.NITRADO_TOKEN }}
        NITRADO_ID: ${{ secrets.NITRADO_ID }}
      run: |
        python gameserver_restart.py 

    - name: Output result to GitHub summary
      run: |
        echo "## Summary of Gameserver Restart" >> $GITHUB_STEP_SUMMARY
        echo "$(python gameserver_restart.py)" >> $GITHUB_STEP_SUMMARY
