name: Upload Files

on:
  workflow_run:
    workflows: ["Push Changes"]
    types:
      - completed

jobs:
  upload_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check for files to upload
        run: |
          mkdir -p temp_upload
          for file in ${{ github.event.outputs.files }}; do
            if [[ ! "$file" =~ ^\.github/ && "$file" != "cfgeffectarea.json" && "$file" != "cfgeventspawns.xml" && "$file" != "db/events.xml" ]]; then
              cp "$file" temp_upload/
            fi
          done

      - name: Upload to FTP
        if: success() && !steps.get_changed_files.outputs.files == ''
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: temp_upload/
          server-dir: /dayzxb_missions/

      - name: Clean up
        run: rm -rf temp_upload/
